### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by moreabs** [FabianIsensee/BatchViewer#1]
Dear FabianIsensee:
i used your BatchViewer in colab to visualize 3D MRI data with 4D numpy arrays (4,96,96,96) but my runtime restarted and colab crashed. whats the problem? how can i fix it?

**Comment by FabianIsensee** [comment]
Hi,
I have no experience with colab. Batchviewer will open a QT window and I think this is just not possible from within colab.
Best,
Fabian
