### ISSUE TITLE
install Error:

### ISSUE THREAD

**Issue by WMeixiang** [FabianIsensee/BatchViewer#3]
Hi, I want to install BatchViewer, while I met an install Error:  Could not find a version that satisfies the requirement BatchViewer (from versions: none)...
![image](https://user-images.githubusercontent.com/47051563/71897104-88e54580-3190-11ea-81e6-7aefd7a44900.png)

How can I handle it??

**Comment by FabianIsensee** [comment]
You clone the repository, cd into the repository and then `pip install .`

**Comment by WMeixiang** [comment]
Thank you! I can install BatchViewer, while I also met import Error:
![image](https://user-images.githubusercontent.com/47051563/72069756-d5f92100-3322-11ea-9abf-4850ba65a19f.png)
![image](https://user-images.githubusercontent.com/47051563/72069909-312b1380-3323-11ea-9348-0dc41fb68c1a.png)

**Comment by FabianIsensee** [comment]
You need to install pyqt5 as well
