### ISSUE TITLE
Saggital View

### ISSUE THREAD

**Issue by songeeu** [FabianIsensee/BatchViewer#4]
Hi Fabian.  Thank you for this tool it is very effective.  I am only seeing the saggital view when I follow the (c,x,y,z) order.  I am using nibabel to read image and masks.  Is this intentional or am I missing something?  Thank you so much!

**Comment by FabianIsensee** [comment]
Hi, this tool was not written with medical images in mind. If you want to see a different plane, you need to transpose the array

view_batch(array.transpose((1, 2, 0)))

Best,
Fabian

**Comment by songeeu** [comment]
Thank you Fabian!  That is what I ended up doing and just wanted to make sure that I did not mess up the data...  Very nice (fast) tool so thanks for that.
